FROM python:3.7

ENV PYTHONUNBUFFERED 1

#RUN apt-get update -y && \
#    apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY web/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

EXPOSE 5000 80 443 22

ENTRYPOINT ["python", "app.py" ]

#CMD [ "app.py" ]