version: '3'

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
      - "5000"
    environment:
      - FLASK_ENVIRONMENT=development
      - FLASK_ENV=development
      - POST_DEPLOYMENT_ENVIRONMENT=local
      - HTTPLIB2_CA_CERTS=/zscaler.pem
      - SSL_CERT_FILE=/zscaler.pem
      - REQUESTS_CA_BUNDLE=/zscaler.pem

    env_file:
      - .env

    #    links:
#      - postgres:postgres
    volumes:
      - .:/app
      - ${PWD}/zscaler.pem:/zscaler.pem
      - ${PWD}/container-files/client_secrets.json:/client_secrets.json

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
#      - .:/app/static
      - .:/app
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .env

    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
#  web-data: